### ISSUE TITLE
Question: Top-mounted diodes and case clearance

### ISSUE THREAD

**Issue by breckenedge** [zzeneg/picachoc36#1]
Thanks for releasing this project. I'm eager to get my hands on one.

Any clearance issues with the top-mount diodes and the case? I saw your BOM indicated `1N4148 SOD-123 SMD` diodes, which look to be about 1.4mm tall. Is that right? Do you have any pics without the case on?

I'm happy to order the parts and provide photos for a build guide if that helps.

**Comment by zzeneg** [comment]
Thanks!

I think the only pic without case I have is this one - ![image](https://raw.githubusercontent.com/zzeneg/picachoc36/main/images/build.jpg)

No clearance issues, case has empty spaces where diodes are located
![image](https://user-images.githubusercontent.com/910255/212441597-1b59fa59-7d7f-4dab-b6fd-20d2aee38088.png)

Here you can see diodes inside case 
![image](https://user-images.githubusercontent.com/910255/212441447-4ed047cc-9176-4d6e-a0ce-3e55e86a6fca.png)

I hope it'll work for you and I'd be very greatful for a build guide of course!

**Comment by zzeneg** [comment]
Also I added some details to build guide, hope it makes more sense now. And removed mentioning choc v2 switches🤦

**Comment by breckenedge** [comment]
Oh perfect! I ordered PCBs/Cases from JLC and SMDs/Rotaries/MCUs from Alibaba.

**Comment by zzeneg** [comment]
Yep, it's V1 only! Copy pasted BOM from previous keyboard and didn't notice...
